### ISSUE TITLE
NETStandard version of XamarinClipboardPlugin?

### ISSUE THREAD

**Issue by dfarrNTST** [stavroskasidis/XamarinClipboardPlugin#3]
Is there a NETStandard version of this package available or on the roadmap?  We are moving all of our library development to .NETStandard 2.0.

**Comment by stavroskasidis** [comment]
Yes, I will look into it. It may take me 1-2 days

**Comment by stavroskasidis** [comment]
Done.

I released version 2.0 which is now on .NET standard 1.0.
https://www.nuget.org/packages/Xamarin.Plugins.Clipboard/2.0.0

If for some reason you or someone else cannot migrate their projects to .net standard yet, you can still use the 1.2 version of the package.
