### ISSUE TITLE
Desktop platforms support?

### ISSUE THREAD

**Issue by tzachshabtay** [stavroskasidis/XamarinClipboardPlugin#5]
Any plans to support desktop platforms (Mac, Linux and non-UWP Windows)?
Thanks.

**Comment by stavroskasidis** [comment]
Hmm, I don't see why not, especially If there is demand for it. But I guess it has to be in the context of Xamarin.Forms. Linux and Mac are upcoming Xamarin.Forms platforms correct? Non-UWP is not supported as far as I know

**Comment by tzachshabtay** [comment]
Why does it have to be in the context of Xamarin.Forms? Can't it be made to work universally?

**Comment by stavroskasidis** [comment]
I'll look into it

**Comment by Suplanus** [comment]
Tested it on the mac. Compiles. But at runtime i get this error:
```
This functionality is not implemented in the portable version of this assembly. 
You should reference the NuGet package from your main application project in order to reference the platform-specific implementation.
```

**Comment by stavroskasidis** [comment]
Yeah,there must be a platform implementation, I am updating my mac to look into it.

**Comment by stavroskasidis** [comment]
Added Mac support

**Comment by tzachshabtay** [comment]
That's great, thanks, but it still doesn't include Linux & Windows, right? Can this be added too? I want to be able to use it from Mono or .Net Core.

**Comment by knocte** [comment]
I've contributed a Gtk backend (Linux) here: https://github.com/stavroskasidis/XamarinClipboardPlugin/pull/7
