### ISSUE TITLE
Mac dont work

### ISSUE THREAD

**Issue by Suplanus** [stavroskasidis/XamarinClipboardPlugin#6]
I tried the [fix](https://github.com/stavroskasidis/XamarinClipboardPlugin/issues/5#event-1497780092). But the Clipboard is empty. It was set by the code but there is no content

I looked into your changes... i implemented it the same way and this works. But the CrossClipboard not:

```csharp
private static string[] pboardTypes = new string[] { "NSStringPboardType" };
partial void ButtonCopy(NSButton sender)
{
    NSPasteboard.GeneralPasteboard.DeclareTypes(pboardTypes, null);
    NSPasteboard.GeneralPasteboard.SetStringForType(TextFieldLicences.StringValue, pboardTypes[0]);

    // todo: Dont work: 
    // CrossClipboard.Current.SetText(TextFieldLicences.StringValue);
}
```

I think the problem is this in [your code](https://github.com/stavroskasidis/XamarinClipboardPlugin/commit/292c3a1da2b4a0f1581d983d6d605e6b5e40be0d#diff-8c4b17b67bd28199fe9bee08d643909aR23):
```csharp
private readonly string[] pboardTypes = { "NSPasteboardTypeString" };
```
Should be:
```csharp
private readonly string[] pboardTypes = { "NSStringPboardType" };
```

**Comment by stavroskasidis** [comment]
I am sorry I am not a Mac developer. However I found out that "NSStringPboardType" is deprecated 
https://developer.apple.com/documentation/appkit/nsstringpboardtype

CrossClipboard works on my test app, which is the latest mac unified framework whatever (targets Xamarin.Mac20)

Are you using something else? Can you provide a test app so that I can reproduce it? I think it is possible to support both the latest and the legacy.

**Comment by stavroskasidis** [comment]
See also here 
https://stackoverflow.com/questions/598587/writing-a-string-to-nspasteboard

**Comment by Suplanus** [comment]
I tested it with both but only `NSStringPboardType` works... i attached the test app.
[ClipBoardTest.zip](https://github.com/stavroskasidis/XamarinClipboardPlugin/files/1770977/ClipBoardTest.zip)

**Comment by stavroskasidis** [comment]
Thank you for the test project. I will look into it

**Comment by stavroskasidis** [comment]
Btw, what is your Max OS X version ?

**Comment by stavroskasidis** [comment]
It seems that the behavior is tied to the mac os x version. 

`NSStringPboardType ` is considered obsolete after version 10.6 and the new one is `NSPasteboardTypeString `. However `NSStringPboardType ` seems to work on my mac which is version 10.12

I will change the code to use `NSStringPboardType ` for backwards compatibility. I will tackle this again in the future if necessary.

**Comment by stavroskasidis** [comment]
Please update to https://www.nuget.org/packages/Xamarin.Plugins.Clipboard/2.1.3
and see if that works for you

**Comment by Suplanus** [comment]
Works 🦄 😘
